version: "0.2"
language: en
words:
  - aliceblue
  - alphabio
  - antiquewhite
  - b_short
  - biome
  - blanchedalmond
  - blueviolet
  - Bundlephobia
  - burlywood
  - cadetblue
  - cornflowerblue
  - cornsilk
  - css
  - csstree
  - currentcolor
  - darkcyan
  - darkgoldenrod
  - darkgray
  - darkgreen
  - darkgrey
  - darkkhaki
  - darkmagenta
  - darkolivegreen
  - darkorange
  - darkorchid
  - darkred
  - darksalmon
  - darkseagreen
  - darkslateblue
  - darkslategray
  - darkslategrey
  - darkturquoise
  - darkviolet
  - deeppink
  - deepskyblue
  - dimgray
  - dimgrey
  - directional
  - dodgerblue
  - dts
  - Flexbox
  - floralwhite
  - forestgreen
  - gainsboro
  - ghostwhite
  - greenyellow
  - hotpink
  - hsl
  - hsla
  - indianred
  - justfile
  - lavenderblush
  - lawngreen
  - lemonchiffon
  - lightcoral
  - lightcyan
  - lightgoldenrodyellow
  - lightgray
  - lightgreen
  - lightpink
  - lightsalmon
  - lightseagreen
  - lightskyblue
  - lightslategray
  - lightslategrey
  - lightsteelblue
  - lightyellow
  - limegreen
  - longhand
  - Longhands
  - mediumaquamarine
  - mediumblue
  - mediumorchid
  - mediumpurple
  - mediumseagreen
  - mediumslateblue
  - mediumspringgreen
  - mediumturquoise
  - mediumvioletred
  - midnightblue
  - mintcream
  - mistyrose
  - navajowhite
  - oldlace
  - olivedrab
  - orangered
  - palegoldenrod
  - palegreen
  - paleturquoise
  - palevioletred
  - papayawhip
  - peachpuff
  - pnpm
  - powderblue
  - rebeccapurple
  - regex
  - rgb
  - rgba
  - rosybrown
  - royalblue
  - saddlebrown
  - sandybrown
  - seagreen
  - shorthand
  - skyblue
  - slateblue
  - slategray
  - slategrey
  - springgreen
  - steelblue
  - tsconfig
  - url
  - vitest
  - whitesmoke
  - xtend
  - yellowgreen
ignorePaths:
  - node_modules
  - lib
  - dist
  - .git
  - "*.lock"
  - "*.log"
